AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gopher-tweets

Globals:
  Function:
    Timeout: 5

Parameters:


Resources:
  GopherTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/gopher-tweets
      Handler: gopher-tweets
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY:
          TWITTER_CONSUMER_SECRET:
          TWITTER_ACCESS_TOKEN:
          TWITTER_TOKEN_ACCESS_TOKEN_SECRET:

Outputs:
  GopherTweetsHelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for Lambda Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GopherTweetsFunction:
    Description: "Function ARN"
    Value: !GetAtt GopherTweetsFunction.Arn
  GopherTweetsFunctionIamRole:
    Description: "IAM Role created for Gopher Tweets function"
    Value: !GetAtt GopherTweetsFunctionRole.Arn
