version: 2.1

orbs:
  aws-sam-serverless: circleci/aws-sam-serverless@3.0.0

jobs:
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-v1-{{ checksum "go.sum" }}
      - run:
          name : Unit tests
          command: go test ./...
      - save_cache:
          key: go-modules-v1-{{ checksum "go.sum" }}
          paths:
            - /root/go/pkg/mod

workflows:
  version: 2
  build_and_push:
    jobs:
      - test
