version: 2.1

executors:
  default:
    docker:
      - image: xliiauo/go-sam-builder:latest

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-v1-{{ checksum "go.sum" }}
      - run:
          name : Unit tests
          command: go test ./...
      - save_cache:
          key: go-modules-v1-{{ checksum "go.sum" }}
          paths:
            - /root/go/pkg/mod
  build-deploy:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-v1-{{ checksum "go.sum" }}
      - run:
          name : Build artifacts
          command: make
      - run:
          name: Deploy stack
          command: make deploy
                     TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
                     TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
                     TWITTER_LOGIN_CALLBACK=${TWITTER_LOGIN_CALLBACK}
                     FRONTEND_REDIRECT=${FRONTEND_REDIRECT}
                     SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - save_cache:
          key: go-modules-v1-{{ checksum "go.sum" }}
          paths:
            - /root/go/pkg/mod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build-deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
